import http.client
import os
import unittest
from urllib.request import urlopen, Request
from urllib.error import HTTPError

import pytest

BASE_URL = "http://localhost:5000"
BASE_URL_MOCK = "http://localhost:9090"
DEFAULT_TIMEOUT = 2  # in secs

@pytest.mark.api
class TestApi(unittest.TestCase):
    def setUp(self):
        self.assertIsNotNone(BASE_URL, "URL no configurada")
        self.assertTrue(len(BASE_URL) > 8, "URL no configurada")

    def test_api_add(self):
        url = f"{BASE_URL}/calc/add/1/2"
        response = urlopen(url, timeout=DEFAULT_TIMEOUT)
        self.assertEqual(
            response.status, http.client.OK, f"Error en la petici贸n API a {url}"
        )
        self.assertEqual(
            response.read().decode(), "3", "ERROR ADD"
        )

    def test_api_sqrt(self):
        url = f"{BASE_URL_MOCK}/calc/sqrt/64"
        response = urlopen(url, timeout=DEFAULT_TIMEOUT)
        self.assertEqual(
            response.status, http.client.OK, f"Error en la petici贸n API a {url}"
        )
        self.assertEqual(
            response.read().decode(), "8", "ERROR SQRT"
        )

    def test_api_multiply(self):
        url = f"{BASE_URL}/calc/multiply/3/4"
        response = urlopen(url, timeout=DEFAULT_TIMEOUT)
        self.assertEqual(
            response.status, http.client.OK, f"Error en la petici贸n API a {url}"
        )
        self.assertEqual(
            response.read().decode(), "12", "ERROR MULTIPLY"
        )

    def test_api_divide(self):
        url = f"{BASE_URL}/calc/divide/8/2"
        response = urlopen(url, timeout=DEFAULT_TIMEOUT)
        self.assertEqual(
            response.status, http.client.OK, f"Error en la petici贸n API a {url}"
        )
        self.assertEqual(
            response.read().decode(), "4.0", "ERROR DIVIDE"
        )

    def test_api_divide_by_zero(self):
        try:
            url = f"{BASE_URL}/calc/divide/8/0"
            req = Request(url, headers={"Accept": "*/*"})
            response = urlopen(req, timeout=DEFAULT_TIMEOUT)
            self.fail(f"Se esperaba HTTP 406, pero se obtuvo {response.status}")
        except HTTPError as e:
            if e.code == http.client.NOT_ACCEPTABLE:
                self.assertEqual(e.code, http.client.NOT_ACCEPTABLE, f"Se esperaba HTTP 406, pero se obtuvo {e.code}")

if __name__ == "__main__":  # pragma: no cover
    unittest.main()
